<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Timesheet.Application\Timesheet.Application.csproj" />
    <ProjectReference Include="..\Timesheet.Domain\Timesheet.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Blazor" Version="15.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="seed-timesheets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
